apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: elasticsearch
  labels:
    io.kompose.service: elasticsearch
spec:
  selector:
    io.kompose.service: elasticsearch
  type: LoadBalancer
  ports:
  - name: 9200
    port: 9200
    targetPort: 9200
  - name: 9300
    port: 9300
    targetPort: 9300
status:
    loadBalancer: {}
#type: LoadBalancer
